# Generated by Django 4.0.6 on 2022-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
