# Generated by Django 4.0.6 on 2022-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_photos_photo_url_photos_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='tile_url',
        ),
        migrations.AddField(
            model_name='photos',
            name='tile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
